### ISSUE TITLE
Create docker-compose.yml with message-bus and database

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#1]
Provided [here](https://github.com/riesgos/async/blob/main/docker-compose.yml)

**Comment by nbrinckm** [comment]
Not sure if the database should depend on the queue service. From my perspective they are completely seperated for their startup process.

(And in any case: Startup of the pulsar is a little bit weird. We use an `wait-for-it` shell script to make sure that it started properly).

**Comment by nbrinckm** [comment]
From our earthquake explorer dockerfiles:

```
ADD https://git.gfz-potsdam.de/api/v4/projects/1796/repository/files/wait-for-it.sh/raw?ref=81b1373f17855a4dc21156cfe1694c31d7d1792e /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
```

And in the start scripts:

```
/wait-for-it.sh --timeout=0 "${PULSAR_HOST}:${PULSAR_PORT}"
```

**Comment by nbrinckm** [comment]
Maybe those will be useful for the wrappers later.

**Comment by nbrinckm** [comment]
If I could suggest another change (just to be sure):

```
environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: 'true'
```

for the pulsar (even if it should not be that dangerous for the local development setup - but often those are used to create a staging / prod version the docker-compose files).
