### ISSUE TITLE
Requests from Frontend to Database

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#15]
- [x] List of all product-types 
    -  `select distinct wps_identifer from complex_outputs `
- [x] List all products of a given type
    - `select id from complex_outputs where wps_identifier='shakeMapFile'`
- [x] List all inputs that led to a given product
     - ```
        select ci.id 
        from complex_inputs as ci
        join jobs as j on j.id = ci.job_id
        join complex_outputs as co on co.job_id = j.id
        where co.id = <selected-product-id>
        ```
- [x] List all outputs derived from a given product
    - ```
        select co.id 
        from complex_outputs as co
        join jobs as j on j.id = co.job_id
        join complex_inputs as ci on ci.job_id = j.id
        where ci.id = <selected-product-id>
      ```
- [x] For orders-view: Which paras have not yet been used?
    - Example: let's say the user wants to order calculations based on shakemap-42. He's also decided that he wants to use the schema SARA_v1.0. Which exposure-models should the user be given to chose from? The orders-form should only suggest to the user those exposure-models which have not yet been used in combination with shakemap-42 and SARA_v1.0.
    - Maybe a little easier is the following question ... let's ignore shakemap-42 for now and only focus on SARA_v1.0. Given SARA_v1.0, which exposure-models have already been used?
    - ```
        select lo.* 
        from literal_outputs as lo
        join jobs as j on lo.job_id = j.id
        join literal_input as ci on ci
        where ci.id = <id-SARA_v1.0>
        and lo.wps_identifier = 'model'
      ```

**Comment by MichaelLangbein** [comment]
- Can we unite `complex_outputs` and `complex_inputs`?
    - We might, but that comes under `lessons learned`. For now we keep the current stable state.
-

**Comment by MichaelLangbein** [comment]
@nbrinckm : In the description we've collected the kinds of requests that @boeckMt and I will use in the catalog- and order-views. The queries are way simplified, of course. Especially the last query (`Which paras have not yet been used?`) seems a little more complicated. Here some frontend-side processing might be in order, too. Do you think we can serve (part of) these queries via FastAPI?

**Comment by nbrinckm** [comment]
I have a little bit different understanding about what is a product itself. Please let me explain.

With your current idea, you would go to the complex outputs. This can be useful when the outputs are highly different. But in our case in RIESGOS those different outputs are still considering one thing:

- in shakyground we get two outputs for the shakemaps (one as xml, one as wms). Both are two different complex outputs entries but they are about the very same thingy. Here is the the special case that both outputs have the very same output wps identifier - we could argue that those make it one bundled product, but when we consider other cases we don't even have this situations.
- Consider deus: We currently have the merged_output, the shapefile summary & the json file that describes the columns in the shapefile (together with some global statistics). They all are different complex outputs, they all have different output wps identifiers. But they still describe one product from my point of view.

So overall I would think about products as jobs that succeeded. That would give us an shakyground output, an assetmaster output, a modelprop output and a deus output.

So I would see it more like this:

products:
```sql
select jobs.id, processes.wps_identifier || ' output (' || jobs.id || ')' as name, jobs.process_id as product_type_id
from jobs
join processes on processes.id = jobs.process_id
where jobs.status = 'Succeeded'
```

Similar, the product types should be named for processes for that we have jobs that succeeded.

```sql
select distinct processes.id, processes.wps_identifier || ' output' as name
from processes
join jobs on jobs.process_id = processed.id
where jobs.status = 'Succeeded'
```

I tried to make those into endpoints in the pull request here (https://github.com/riesgos/async/pull/16).

**Comment by nbrinckm** [comment]
I would make the requests for products that are a base for another product in a similar way, as well as the derived products.

**Comment by nbrinckm** [comment]
In one commit I added the endpoints:

/product-types
/product-types/{product_type_id}
/products
/products/{product_id}

(While product type id is more or less equivalent to the process id, and product id is the same as the job id)

And now I added 

/products/{product_id}/derived-products
/products/{product_id}/base-products

Currently those work only for one level (so no link direct link between the deus outputs & quakeledger), but it would be possible to add an recursive query parameter as well.

**Comment by nbrinckm** [comment]
Regarding to the parameterization questions:

I guess the backend can't say overall which things haven't be used yet, as we only track what was done & don't know the set of possible input parameters.

However, we can say what was used for one process.


```sql
select literal_inputs.*
from processes
join jobs on jobs.process_id = processes.id
join literal_inputs on literal_inputs.job_id = jobs.id
where processes.id = ?
```

Similar for the bbox inputs, the complex_inputs, complex_inputs_as_values, complex_outputs_as_inputs.

That way we can explore the feature set that was already used.

However, at the moment those queries are not that easily possible from the backend. But the only thing that is missing from my perspective at the moment, is the filter for the process id.

**Comment by nbrinckm** [comment]
Ok, now I added process id filter for all the input endpoints.

with
/literal-inputs?process_id={process_id}

we can now extract all the values that we had used for a specific process so far.
As we have the job ids we all the inputs, we now which combinations are done so far:


Say we query for shakeyground:

/literal-inputs?process_id={process_id_of_shakyground}

| id | job_id | wps_identifier | input_value |
|-----|--------|---------------------|----------------|
| 123 | 41 | gmpe | Abrahamson |
| 124 | 41 | vsgrid | Usgs |
| 166 | 42 | gmpe | Montalva  |
| 167 | 42 | vsgrid | Usgs |
| 177 | 43 | gmpe | Abrahamson |
| 178 | 43 | gmpe | Microzonation |

From that we can extract the gmpe & vsgrid values (but I would like that the frontend could now that apriori).

But what we also can is to extract that we don't have a run for Montalva (as gmpe) and Microzonation (as vsgrid) yet.

In a similar way we can extract the values already processed for any complex input & the bbox inputs as well.
And we can easily make suggestions on what to process next.

**Comment by nbrinckm** [comment]
Now it should also be possible to use the process id filter for the complex outputs. That way we can extract what we already computed (the shakemaps for example).

**Comment by MichaelLangbein** [comment]
This is excellent! Thanks a lot!
