### ISSUE TITLE
Frontend: angular-app connected to message-bus

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#2]
Must go through node-proxy, because [pulsar-client](https://www.npmjs.com/package/pulsar-client) is just a wrapper around pulsar's c++-client.

**Comment by boeckMt** [comment]
> Must go through node-proxy, because [pulsar-client](https://www.npmjs.com/package/pulsar-client) is just a wrapper around pulsar's c++-client.

It was discussed to use WebSockets for this.


@MichaelLangbein and @nbrinckm do we already have a url for the WebSocket connection?

**Comment by boeckMt** [comment]
@MichaelLangbein where should I place the code of the frontend?

**Comment by MichaelLangbein** [comment]
@boeckMt : Would you place it directly in this repository? Ideally in a subdirectory `frontend`. Thanks!

**Comment by MichaelLangbein** [comment]
> @MichaelLangbein and @nbrinckm do we already have a url for the WebSocket connection?

There is an API available, but  for now the best way to go about this would probably be to talk to a local instance of pulsar instead.
(I'm sending you the public api per email in a bit!)

**Comment by boeckMt** [comment]
@MichaelLangbein the test frontend is now in branch https://github.com/riesgos/async/tree/add-frontend

**Comment by MichaelLangbein** [comment]
I've included a websocket-based pulsar-client and merged this branch.

**Comment by MichaelLangbein** [comment]
Here's a mockup of what our user-experience might look like:

[async-arch.pdf](https://github.com/riesgos/async/files/9193117/async-arch.pdf)

**Comment by MichaelLangbein** [comment]
- show all derived from this: lists all products derived from this in a modal in card shape.

**Comment by MichaelLangbein** [comment]
Alternatively we can have the user calculate *forward* from a given product. Here's what the UI in that case might look like.

[async-arch_forward.pdf](https://github.com/riesgos/async/files/9196227/async-arch_forward.pdf)

**Comment by MichaelLangbein** [comment]
Decisions: 
 - we'll use forward-processing strategy.
