### ISSUE TITLE
Shakemap schema validation

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#46]
- Currently, shakemaps need a "originator" field
- They now have a superfluous field "seed"
-

**Comment by MichaelLangbein** [comment]
@Michael: upload a sample of Hugo's resampler output file.

**Comment by MichaelLangbein** [comment]
Test new file against WPS'es

**Comment by HugoRosero** [comment]
The resampler has been updated. Now it reads the grid headers for generating the noise on multiple intensity measures (PGA, PGV, SA at different periods are supported), as long as they come with the standard deviation with the prefix STD. 

@bpross-52n The WPS is ready for deployment

**Comment by nbrinckm** [comment]
I would not suggest to put the seed in the `<event>` tag, as that should specify the event itself that is used as the source of the overall shaking that  we model with the shakemap.

Instead I would suggest to store the seed in the `shakemap_version` field. It could then look like this:

```
<shakemap_grid 
    ...
   shakemap_version="seed=42"
   ...
>
  ...
</shakemap_grid>
```

This field is more intended to store information about the processing of the shakemap (so it makes more sense for my side).
Also in the schema that we have & use, this field is specified as `string`, so we can store there quite a lot of information. I would suggest to have some key value pairs as `key1=value1,key2=value2`. This is also a pattern that a python library like https://pypi.org/project/environs/ can handle when parsing key value pairs from env variables (so the logic to parse those values is already integrated in some good libraries).

**Comment by MichaelLangbein** [comment]
@Nils & @Hugo: move seed into "shakemap_version"
@Benni: re-deploy

**Comment by nbrinckm** [comment]
Ok, there is the pull request for the resampler: https://github.com/HugoRosero/ShakeMapSampler/pull/1

@HugoRosero I wasn't able to run the test, I still hope it is ok for you.

**Comment by nbrinckm** [comment]
As Hugo merged the PR, the validation runs just fine.

I also pushed the code with that I do this validation:
https://github.com/nbrinckm/ShakemapValidaton

Tested with both xmllint & the java code from our wps wrapper.

**Comment by nbrinckm** [comment]
I also made a test that the example from Hugo can be used in deus. So with all that in place all those validations should work fine.

**Comment by MichaelLangbein** [comment]
New code being deployed by @bpross-52n ; needs to update build script first.

**Comment by bpross-52n** [comment]
I have deployed the new code.
