### ISSUE TITLE
Authentication and user-management

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#62]
How should we do user-management?

We should not allow everyone to access our app and send orders to the backend.
We could only allow certain quotas of calculations per registered user.
But really, I think we only have one real user: Hugo.

I've removed the `register` section from the frontend so nobody can register through the frontend anymore. 
I think we should probably do the same with the backend, and only allow a certain user to login at all.
In fact, we could probably set that user's email and password at build-time with environment-variables, right?

**Comment by nbrinckm** [comment]
Yes that would be possible.

We would just need to add another section of startup code:
- read env variables
- add the user with the crud methods
- start the regular app
- (optional: Remove the endpoint to register).

**Comment by nbrinckm** [comment]
I think this here is a good point to the docs for handling the startup: https://fastapi.tiangolo.com/advanced/events/

**Comment by MichaelLangbein** [comment]
Thanks a lot @nbrinckm for setting this up so quickly! Issue resolved.
