### ISSUE TITLE
HTTP retry: No need to sleep after last attempt

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#69]
[asyncwrapper/src/main/kotlin/org/n/riesgos/asyncwrapper/utils/RetryUtils.kt](https://github.com/riesgos/async/pull/59/files/9f1871d1f47f26cde693bf0affcb0a49a4319590#diff-9febe8d35540e0bea5dab81733843a2e6a6d6e8507d3e2cb84e8dfe88bb70dee)
```kotlin
            // ignore this specific exception and retry
            retryCount++
            lastException = ex
            Thread.sleep(sleepTimeMilliSeconds)
```
I realized that we also sleep if we failed on the last attempt - one of the errors I made when I wrote the first version of this retry decorator.

Maybe we can a simple if statement here, so that we don't sleep when we already know that there will be no last attempt.

**Comment by arnevogt** [comment]
fixed in #59
