### ISSUE TITLE
Improve build: use cached maven-dependencies

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/async#86]
For downloads to be  cached:

- I'd need them to be in a separate layer in a docker-file.
- Or I'd need them to be downloaded upon creation of an image, which is only restarted on docker-compose up.
- Or I'd need to share the downloaded maven-packages from my local disk via mount 

Currently done manually: 
`docker-compose up` and then `docker exec -ti riesgos-mvn-builder mvn clean package -DskipTests=true`

When I used the docker compose run it always took a new docker-container. In that case the folder in which it stored the downloaded files is a complete fresh one.
So we would need to mount it within within the docker-compose file. 

Whereas `run.sh` does `docker compose run mvn mvn clean package -DskipTests=true`, which creates a new container without maven-packages.

**Comment by nbrinckm** [comment]
I think this solution is pretty simple at the end. It is just about adding a volume in the docker-compose file.

**Comment by MichaelLangbein** [comment]
I think so, too! If you actually have a little time for this right now, feel free to create a PR.
